### ISSUE TITLE
运行闪退

### ISSUE THREAD

**Issue by JustinNick** [animalize/QuanTangshi#3]
项目刚运行时就直接闪退报下面的错误
java.lang.RuntimeException: Unable to start activity ComponentInfo{animalize.github.com.quantangshi/animalize.github.com.quantangshi.MainActivity}: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (Sqlite code 14): Could not open database, (OS error - 2:No such file or directory)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2451)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:150)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
                                                    Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (Sqlite code 14): Could not open database, (OS error - 2:No such file or directory)
                                                       at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:217)
                                                       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:201)
                                                       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:493)
                                                       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:194)
                                                       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183)
                                                       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:827)
                                                       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:811)
                                                       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
                                                       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:689)
                                                       at com.readystatesoftware.sqliteasset.SQLiteAssetHelper.getReadableDatabase(SQLiteAssetHelper.java:264)
                                                       at animalize.github.com.quantangshi.Database.MyAssetsDatabaseHelper.getDBPath(MyAssetsDatabaseHelper.java:24)
                                                       at animalize.github.com.quantangshi.Database.MyDatabaseHelper.init(MyDatabaseHelper.java:51)
                                                       at animalize.github.com.quantangshi.Database.MyDatabaseHelper.getPoemCount(MyDatabaseHelper.java:78)
                                                       at animalize.github.com.quantangshi.MainActivity.onCreate(MainActivity.java:37)
                                                       at android.app.Activity.performCreate(Activity.java:6367)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:150) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5621) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by animalize** [comment]
似乎没能把`全唐诗的sqlite数据库`从`assets`里解压到`程序的文件目录`里。

能否提供模拟器的详细版本？有没有修改模拟器的存储设置？

**Comment by animalize** [comment]
想起来了，可能是没有生成全唐诗数据库、并把这个数据库文件放到assets目录下。

请看主页Readme的**编译指南**部分。

**Comment by JustinNick** [comment]
你这个还需要Python生成数据库数据啊？

**Comment by JustinNick** [comment]
现在能运行了，但是点击首页的“开始”直接闪退了，估计是数据为空

Process: animalize.github.com.quantangshi, PID: 17871
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{animalize.github.com.quantangshi/animalize.github.com.quantangshi.UIPoem.OnePoemActivity}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2451)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511)
                                                                                      at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:150)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
                                                                                   Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
                                                                                      at android.database.AbstractCursor.checkPosition(AbstractCursor.java:460)
                                                                                      at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
                                                                                      at android.database.AbstractWindowedCursor.getBlob(AbstractWindowedCursor.java:44)
                                                                                      at animalize.github.com.quantangshi.Database.MyDatabaseHelper.getPoemById(MyDatabaseHelper.java:118)
                                                                                      at animalize.github.com.quantangshi.UIPoem.OnePoemActivity.toPoemByID(OnePoemActivity.java:182)
                                                                                      at animalize.github.com.quantangshi.UIPoem.OnePoemActivity.onCreate(OnePoemActivity.java:135)
                                                                                      at android.app.Activity.performCreate(Activity.java:6367)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511) 
                                                                                      at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:150) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5621) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by JustinNick** [comment]
我看了下使用Python生成的tangshi.db这个数据库，里面是空的。

**Comment by JustinNick** [comment]
apk文件是1.65mb，但是tangshi.db文件为8kb，数据库查看时，里面为空

**Comment by animalize** [comment]
看来没有生成全唐诗数据库，如果不想折腾，从.apk里提取（解压.apk）一个也行。

文件名`tangshi.db.zip`，把它放到assets目录下。

**Comment by JustinNick** [comment]
解压得到的tangshi.db.zip里面的内容是乱码

**Comment by animalize** [comment]
`tangshi.db.zip`里只有一个文件`tangshi.db`，这是一个sqlite3数据库文件。

把`tangshi.db.zip`放到assets目录下即可，需要手工创建assets目录。

**Comment by JustinNick** [comment]
不管把tangshi.db.zip这个放在main/assets下，还是放在main/assets/databases下，都报错
这是报的错：
 Process: animalize.github.com.quantangshi, PID: 17378
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{animalize.github.com.quantangshi/animalize.github.com.quantangshi.UIPoem.OnePoemActivity}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2451)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511)
                                                                                      at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:150)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
                                                                                   Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
                                                                                      at android.database.AbstractCursor.checkPosition(AbstractCursor.java:460)
                                                                                      at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
                                                                                      at android.database.AbstractWindowedCursor.getBlob(AbstractWindowedCursor.java:44)
                                                                                      at animalize.github.com.quantangshi.Database.MyDatabaseHelper.getPoemById(MyDatabaseHelper.java:118)
                                                                                      at animalize.github.com.quantangshi.UIPoem.OnePoemActivity.toPoemByID(OnePoemActivity.java:182)
                                                                                      at animalize.github.com.quantangshi.UIPoem.OnePoemActivity.onCreate(OnePoemActivity.java:135)
                                                                                      at android.app.Activity.performCreate(Activity.java:6367)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511) 
                                                                                      at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:150) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5621) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 

然后我解压这个tangshi.db.zip，打开tangshi.db这个数据库发现里面是乱码，估计是直接解压apk包导致的

**Comment by animalize** [comment]
> 不管把tangshi.db.zip这个放在main/assets下，还是放在main/assets/databases下，都报错

得把程序删了，再装一遍。因为程序现在认为已经成功解压。  
位置应该是`main/assets/databases`

> 然后我解压这个tangshi.db.zip，打开tangshi.db这个数据库发现里面是乱码，估计是直接解压apk包导致的

只要校验通过，应该就没问题。它是sqlite3的格式，需要用特定的工具才能查看，比如SQLiteStudio。
